docs/Code.rst
docs/Developing.rst
docs/Installation.rst
docs/Overview.rst
docs/index.rst

Fix #66 by correctly indenting the subtitles of each section of the docs

Set titles of section for automatic toctree

---

.coveragerc
.travis.yml
CHANGELOG.md
README.md
tests/test_requirements.txt

Fix #54
To link travis and coveralls.io
```
script: "add here the code for coverage test"
after_success: "add here code to send coveralls test results"
```
Description of steps:
- `pip install coverage==4.5`
- `python-coveralls`
Note : the version > 5 of `coverage` is not compatible with `python-coveralls`, so version 4.5 was chosen.
- open a [coveralls.io](https://coveralls.io) account with signup from github
- look for the `repo_token` on the [mvs_eland repo](https://coveralls.io/github/rl-institut/mvs_eland) on coveralls.io
- copy this into the [secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets) of the mvs_eland repository on github (Settings-->Secrets-->Add a new secret), with secret name `coverage_token`
Some …

Add coverage badge to readme

---

CHANGELOG.md
mvs_eland_tool/mvs_eland_tool.py

This PR contains two minor fixes:
- `**kwargs` of `main()` were overwritten by default parameters - I changed the order of updating.
- Input directory of csv files specified by user is handed to `load_data_from_csv.create_input_json()`

Minor fixes

---

src/C0_data_processing.py
src/D1_model_components.py
tests/constants.py

Solution: File path for multiple inputs missed TIME_SERIES
`
file_path = os.path.join(settings["path_input_folder"], TIME_SERIES, file_name)`
Closes #163

Bugfix: Enable multiple inputs/outputs

---

inputs/mvs_config.json
src/D0_modelling_and_optimization.py

Fixes 
```
File "mvs_eland/src/D0_modelling_and_optimization.py", line 103, in run_oemof
if dict_values["simulation_settings"]["plot_nx_graph"]["value"] == True:
TypeError: string indices must be integers
```
This error occurred with the [example inputs](https://github.com/rl-institut/mvs_eland/tree/dev/inputs) (with json file).

Bug fix TypeError

---

README.md
docs/Installation.rst
mvs_eland_tool/mvs_eland_tool.py

Fix #156
- Add remaining kwargs info to `main()` docstring and documentation

Update kwargs of main func in docstring and in documentation

---

CHANGELOG.md
src/F1_plotting.py

Fix #234 #230 
So in my case there was simply no cost_total_rest, so it turned out to be an empty dataframe that cannot be plotted. I solved it by simply adding an if statement that only plots the dataframe if it's not empty. If it's empty there's a warning. Please feel free to edit the warning message.
- Your_changes

plot only if costs_total_rest is not empty

---

CHANGELOG.md
inputs/csv_elements/energyStorage.csv
inputs/mvs_config.json
src/A1_csv_to_json.py
tests/inputs/csv_elements/energyStorage.csv

Fix #166
- the seperate storage files are not loaded by its column name but by the storage_filename in energyStorage. 
- A new "storage" parameter is introduced to identify storage files without knowing their names. 

add new storage parameter

---

CHANGELOG.md
mvs_eland_tool/mvs_eland_tool.py
src/B0_data_input_json.py
tests/constants.py
tests/test_B0_data_input_json.py

Fix #167 
- Add an argument to the function `load_json` in order to move the json file after reading it
- :x: For new functionalities: Explain in readthedocs

Move mvs_csv_config.json

---

docs/conf.py
mvs_eland_tool/mvs_eland_tool.py
src/A0_initialization.py

The command line options were completely ignored
The command line arguments were completely ignored due to providing default kwargs (introduced in 0702e1b7b7f44116023c1b58554cbc1c353baa31)
- Only assign the default kwargs if no command line arguments were provided
- :x: Write docstrings to your code
- :x: Write test(s) for your new patch of code
- :x: Update the CHANGELOG.md

Fix command line argument bug

---

inputs/csv_elements/simulation_settings.csv
inputs/mvs_config.json
tests/test_benchmark.py

Fix #260 
- Change the default number of days of the simulation to 2, so it takes much less time to test a whole simulation

Improve benchmark tests

---

CHANGELOG.md
tests/test_F1_plotting.py

Fix #297 
- a test is added that checks if an empty dataframe does not create a pieplot

Create a test for plot_a_pie_chart

---

CHANGELOG.md
src/A1_csv_to_json.py
tests/test_A1_csv_to_json.py
tests/test_data/csv_storage_wrong_column_name.csv
tests/test_data/csv_storage_wrong_parameter.csv
tests/test_data/csv_storage_wrong_values.csv

Fix #299 
- change parameter "storage" in A1 and Tests_A1 to "asset_is_a_storage"
- new tests for the storage in Test_A1
- adapt warning names in A1

Add tests for storage in A1

---

tests/test_sensitivity.py

This is to perform sensitivity test of certain parameters: for example making simulations with fuel prices ranging from price_min to price_max with certain price step, and looking at how one or more of the outputs change versus fuel price. The function `single_param_variation_analysis` is general enough to run N simulations varying one parameter. 
- Add function `get_nested_value` to retrieve a value in a nested json structure
- Add function `set_nested_value` to change a value in a nested json structure

Add function to write sensitivity tests

---

CHANGELOG.md
src/C0_data_processing.py
src/E0_evaluation.py
src/E2_economics.py
src/F0_output.py
src/F2_autoreport.py
src/constants_json_strings.py
tests/test_C0_data_processing.py
tests/test_E2_economics.py

Fix #348 
-  Change into constants into "constants_json_strings.py": "annuity_total", "costs_opex_fix"/"costs_cost_om", "costs_opex_var"/"costs_p_dispatch", "costs_upfront", "costs_total" and "costs_om"

Define last global variables

---

CHANGELOG.md
src/C0_data_processing.py

Fix #168
- Deleted code where the files were copied redundantly into the output folder

Do not copy timeseries files twice

---

CHANGELOG.md
tests/test_A0_initialization.py
tests/test_B0_data_input_json.py

- Some folder path were relative and it lead to errors on pytest with conda env on mac

Change relative folder path to absolute in tests files

---

CHANGELOG.md
src/C0_data_processing.py
src/constants.py

Fix #273
Adresses #413 
- The label of storages will - as a general rule - be redefined as `storage label + subasset name` (#273)
- `MaximumCap` is removed from list of required parameters of `energyStorage` (#413)

Storage name readability and MaximumCap in energyStorages

---

.travis.yml
CHANGELOG.md
mvs_eland_tool/__init__.py
mvs_eland_tool/local_deploy.py
mvs_eland_tool/server_deploy.py
mvs_eland_tool/version.py
setup.py
src/F2_autoreport.py

Fix #355 
- Create a module (`mvs_eland_tool/version.py`) to store the version number and date

Version number is only editable in one module

---

CHANGELOG.md
report/assets/styles.css
src/F2_autoreport.py
tests/inputs/csv_elements/energyConsumption.csv
tests/inputs/csv_elements/simulation_settings.csv

Fix #390
- Add functions and HTML components to display logging messages in the web app and PDF of the autoreport

add a section to the autoreport to display logging messages like warnings and errors

---

docs/conf.py

- The readthedocs build online fails, probably because of the sphinx extension

Fix numpy doc import

---

CHANGELOG.md
docs/MVS_parameters.rst
src/C2_economic_functions.py
tests/test_C2_economic_functions.py

Fix #289, fix #247 
**residual value calculation should consider the time value of money when the asset is sold and not the money value at the beginning of the simulation (as it is now)**:
- divide the capex residual by -> (1 + discount_factor) ** (project_life)

residual value calculation of the specific capex

---

CHANGELOG.md
src/D1_model_components.py

Fix #418
- Adapt and add logging messages for components added to the model in D1
--> Fails but fails with same error in `dev` branch

Improve logging messages of D1

---

CHANGELOG.md
src/F2_autoreport.py
src/utils.py

Fix #462 
- The version information are fetched from reading the version.py module and not importing it, therefore preventing circular imports

Read the version.py module's content instead of importing it

---

CHANGELOG.md
requirements.txt
src/F2_autoreport.py
tests/test_A0_initialization.py

Fix #427
- Added `pyppdf` to requirements, calls patch in `F2`

Enable report compilation using `-pdf` on Windows

---

CHANGELOG.md
src/C0_data_processing.py
src/C1_verification.py
tests/test_C1_verification.py

see #119 - does not fix the whole issue
- Display error message when feed-in tariff > electricity price of any  asset in 'energyProvider.csv'.

Display error message when feed-in tariff > electricity price

---

CHANGELOG.md
src/F2_autoreport.py

Fix #481 
- Suppressed the log messages of the Flask server (for report webapp)

Set logging message from Flask server to Error

---

CHANGELOG.md
src/F0_output.py
src/F1_plotting.py

Fix #515 
- Possibility to add an upper bound  on the number of days to display in a timeseries' plot

Allow plotting only a few days of timeseries

---

CHANGELOG.md
src/F1_plotting.py
tests/test_F1_plotting.py

Fix #517
- Color lists for plots are provided by user and are not hard coded anymore

Fix the hardcoded color lists in the figure creation

---

CHANGELOG.md
src/F1_plotting.py

Fix #543 
- Add a warning message if the timeseries of demands or resources are empty

Prevent error if timeseries to plot is empty

---

CHANGELOG.md
src/mvs_eland/C1_verification.py

Fix #550 
- Now diff can also be of type int
Notes:
- There are still some pytests missing for the function, specifically for prices/tariffs provided as a timeseries

Fix C1.check_feedin_tariff()

---

CHANGELOG.md
src/mvs_eland/D2_model_constraints.py
tests/test_D2_model_constraints.py

Fix #554
Adresses #540 
- Add Debug messages for pytests: `D2` 
- Fix incorrectly applied minimal renewable share criterion
- Change `D2.prepare_constraint_minimal_renewable_share`, including logging messages and pytest

Fix faulty minimal renewable share criterion

---

CHANGELOG.md
src/mvs_eland/F2_autoreport.py

Fix #556 
- Change pyppeteer waituntil condition

Fix pdf report generation

---

CHANGELOG.md
docs/Code.rst
docs/files_to_be_displayed/example_docstring.py
src/mvs_eland/A0_initialization.py
src/mvs_eland/A1_csv_to_json.py
src/mvs_eland/C2_economic_functions.py
src/mvs_eland/D2_model_constraints.py
src/mvs_eland/E1_process_results.py
src/mvs_eland/E2_economics.py
src/mvs_eland/E3_indicator_calculation.py
src/mvs_eland/F1_plotting.py
src/mvs_eland/F2_autoreport.py
src/mvs_eland/utils/constants_json_strings.py

Fix #563 
- Change the import path of the modules for automatic docstrings import in `docs/Code.rst`
- Fix the docstrings with math expressions (need to add `r` before the `"""` of the docstring)

Fix readthedoc for code modules

---

CHANGELOG.md
src/mvs_eland/F1_plotting.py

Fix #553
- Change `F1.plot_piecharts_of_costs()` now cites costs with currect currency and avoids decimal numbers
- Fix Graphs of the report now use appropriate currency
:x:  Write docstrings to your code
:x:  For new functionalities: Explain in readthedocs
:x:  Write test(s) for your new patch of code

Fix piecharts to display actual project currency

---

CHANGELOG.md
src/mvs_eland/C0_data_processing.py
src/mvs_eland/C1_verification.py

This should be merged into PR #498; split up due to insecurities.
- Fix optimizedAddCap of non-dispatchable sources: multiply maximumCap by max(timeseries(kWh/kWp)) to fix issue #446
- `timeseries_normalized` are calculated for all `timeseries` of non-dispatchable sources now (before only if `optimizeCap==True`) 

Fix optimizedAddCap of non-dispatchable sources

---

CHANGELOG.md
tests/test_input_folder_parameters.py

Addresses part of #540 
- Write explicit test failure messages hinting to the developer what is the meta cause of the test failure

Improve assert error msg

---

.github/pull_request_template.md
CHANGELOG.md
CONTRIBUTING.md
docs/files_to_be_displayed/example_docstring.py

Fix #540 
- Modify PR template to precise to add assert message and link to example docstring
- Update CONTRIBUTING to add a "Write test for your code" section before the "Run tests locally" one

Include assert message in contribute and PR template

---

CHANGELOG.md
docs/files_to_be_displayed/example_scalar_as_timeseries_energyConversion.csv
docs/simulating_with_the_mvs.rst

Fix #595 
- RTD entry for defining parameters as timeseries
:x:  Write test(s) for your new patch of code (pytests, assertion debug messages)
:x: Update the CHANGELOG.md
:x:  Apply black (`black . --exclude docs/`)
:x:  Check if benchmark tests pass locally (`EXECUTE_TESTS_ON=master pytest`)
<sub>*For more information on how to contribute check the …

Fix rtd for defining parameters as timeseries

---

CHANGELOG.md
docs/simulating_with_the_mvs.rst

Fix #612 
- Correct the URLs that link to the input CSV files in input template directory
<sub>*For more information on how to contribute check the [CONTRIBUTING.md](https://github.com/rl-institut/multi-vector-sim …

Fix broken links to input CSV files in readthedocs

---

CHANGELOG.md
src/multi_vector_simulator/E0_evaluation.py
src/multi_vector_simulator/F0_output.py
src/multi_vector_simulator/F1_plotting.py
src/multi_vector_simulator/F2_autoreport.py
src/multi_vector_simulator/utils/constants_json_strings.py

Fix #617 
- Move the function to parse log messages to E0
- Modify the function to save the logging messages to the output JSON results file

Add log messages to results json file

---

CHANGELOG.md
src/multi_vector_simulator/utils/__init__.py

Fix #631 
`python setup.py develop`
followed by 
`mvs_tool -i tests/inputs/ -ext csv -f -pdf` 
should work now
previously only worked via normal pip install or `python setup.py install`
- If `assets` folder is not found in package look in current folder for `report/assets` folder

Fix issue with report generation in develop install

---

CHANGELOG.md
src/multi_vector_simulator/F2_autoreport.py

Fix #634 
- Correct the case of headings of some sections
- Fit the ES graph within the page boundaries
- Fix the issue of dash tables not being rendered in the PDF report

Fix formatting and rendering issues in the autoreport

---

CHANGELOG.md
src/multi_vector_simulator/utils/__init__.py
tests/test_sensitivity.py

Fix #558
- Moved `get_nested_value`, `set_nested_value`, `split_nested_path` from `tests/test_sensitivity.py` to `src/multi_vector_simulator/utils/__init__.py`

Move functions to manage values in nested dict to utils

---

.gitignore
CHANGELOG.md
CONTRIBUTING.md
MANIFEST.in
docs/Installation.rst
docs/simulating_with_the_mvs.rst
prepare_package.py
setup.py
src/multi_vector_simulator/A0_initialization.py
src/multi_vector_simulator/cli.py
src/multi_vector_simulator/utils/__init__.py
src/multi_vector_simulator/utils/constants.py

Addresses #588, fix #614 
- Add entrypoints for `mvs_tool` and `mvs_report` in `setup.py` (this can be simply typed directly in terminal)
- Create function `utils.copy_inputs_template` to copy input_template from package data_files
- Create `MANIFEST.in` file
- Add entrypoint for `mvs_create_input_template` in `setup.py`
- Create script `prepare_package.py` to add data to package and build dist folder
- Rename PACKAGE_PATH to PACKAGE_DATA_PATH
- Update release protocol within `Contributing.md`
- Remove variable `TEMPLATE_INPUT_PATH` and field `data_files` from `setup.py`
**Test locally**
- in a new environment run `pip install multi-vector-simulator==0.5.0rc13`, then make sure you are not in the mvs repo and run `mvs_tool`, it should create a …

Finalize packaging mvs

---

CHANGELOG.md
src/multi_vector_simulator/A1_csv_to_json.py
src/multi_vector_simulator/C0_data_processing.py
src/multi_vector_simulator/E3_indicator_calculation.py
src/multi_vector_simulator/F0_output.py
src/multi_vector_simulator/utils/__init__.py
src/multi_vector_simulator/utils/data_parser.py
src/multi_vector_simulator/utils/exceptions.py
tests/test_A1_csv_to_json.py
tests/test_C0_data_processing.py

- Warning for missing parameter when parsing inputs from epa to mvs
- New module `exceptions.py` in `multi_vector_simulator.utils` to gather custom MVS exceptions (#656)
- Move A1 and C0 custom exceptions into `multi_vector_simulator.utils.exceptions.py` (#656)

Warn for missing parameters when converting from EPA to MVS format

---

CHANGELOG.md
src/multi_vector_simulator/E1_process_results.py
src/multi_vector_simulator/F2_autoreport.py

Partly addresses #535 
- Reformat the way content is displayed in the demands section of the autoreport

Temporary fix for demands section in the autoreport

---

CHANGELOG.md
src/multi_vector_simulator/E1_process_results.py
src/multi_vector_simulator/F1_plotting.py
src/multi_vector_simulator/F2_autoreport.py

Fix #535 
The two commands I used to run the simulations and generate the reports:
`mvs_tool -i tests/inputs -ext csv -f -pdf`
`mvs_tool -i tests/benchmark_test_inputs/AFG_grid_heatpump_heat -ext csv -f -pdf`
- Divide the demands section of the autoreport sector-wise

Modify autoreport to display demands sector-wise

---

CHANGELOG.md
docs/Overview.rst

Fix #640 
- Update readthedocs with information about the MVS server API and how to use it
:x: Apply black (`black . --exclude docs/`)
<sub>*For more information on how to contribute check the [CONTRIBUTING.md](https://github.com/rl-institut/multi-vector-simulator/ …

Add information regarding the MVS server API to the docs

---

CHANGELOG.md
docs/Code.rst
src/multi_vector_simulator/A0_initialization.py
src/multi_vector_simulator/A1_csv_to_json.py
src/multi_vector_simulator/B0_data_input_json.py
src/multi_vector_simulator/C0_data_processing.py
src/multi_vector_simulator/C1_verification.py
src/multi_vector_simulator/C2_economic_functions.py
src/multi_vector_simulator/D0_modelling_and_optimization.py
src/multi_vector_simulator/D1_model_components.py
src/multi_vector_simulator/D2_model_constraints.py
src/multi_vector_simulator/E0_evaluation.py
src/multi_vector_simulator/E1_process_results.py
src/multi_vector_simulator/E2_economics.py
src/multi_vector_simulator/E3_indicator_calculation.py
src/multi_vector_simulator/E4_verification.py
src/multi_vector_simulator/F0_output.py
src/multi_vector_simulator/F1_plotting.py
src/multi_vector_simulator/F2_autoreport.py
src/multi_vector_simulator/utils/constants.py
src/multi_vector_simulator/utils/constants_json_strings.py
src/multi_vector_simulator/utils/constants_output.py
src/multi_vector_simulator/utils/data_parser.py
src/multi_vector_simulator/utils/exceptions.py
src/multi_vector_simulator/utils/helpers.py

Fix #641 
- Improved `Code.rst` for RTD code documentation
- All `.py` files to add a module description for RTD on top

Add parser description in RTD

---

.github/workflows/main.yml
CHANGELOG.md

Fix github actions pre-dependencies installation.
- Update apt-get before installing pre-dependencies in github actions workflow

Update apt-get before installing pre-dependencies

---

CHANGELOG.md
docs/conf.py
src/multi_vector_simulator/A0_initialization.py

Fix #717 
- Remove logging of log messages from third party libraries in the log file

Disable the logging of imported and third-party libraries

---

CHANGELOG.md
src/multi_vector_simulator/E0_evaluation.py
src/multi_vector_simulator/E3_indicator_calculation.py
src/multi_vector_simulator/F2_autoreport.py
tests/test_benchmark_KPI.py

Addresses part of #703
- Format KPI_UNCOUPLED_DICT to a `pd.DataFrame` 
- Add KPI individual sectors to the report

Reformat KPI energy sector

---

CHANGELOG.md
src/multi_vector_simulator/E3_indicator_calculation.py

Fix #559
-  Delete warning message that is outdated as #559 is solved 

Delete warning message that is outdated as #559 is solved

---

CHANGELOG.md
src/multi_vector_simulator/B0_data_input_json.py

- Update B0_data_input_json.py

Avoid class 'numpy.int32' error

---

.github/workflows/main.yml
CHANGELOG.md

- Allow to run workflow manually from the Actions tab by adding `workflow_dispatch` to `main.yml`

Allow to run workflow manually from the Actions tab

---

CHANGELOG.md
docs/Model_Assumptions.rst

Adress #779
- Adapted structure of component models in RTD to mirror EPA and MVS input data
- Added a note in Energy excess section in RTD (component models) saying that excess sinks are added automatically
:x: Apply black (`black . --exclude docs/`)
*Please mark above checkboxes as …

[RTD] Adapt structure of component models section

---

CHANGELOG.md
src/multi_vector_simulator/utils/data_parser.py
tests/test_E3_indicator_calculation.py

- Fix logging.info message for data parser from EPA to MVS, as identified in rl-institut/mvs_eland_api#10
- Use deepcopy with dict passed to EPA/MVS parser

Fix data parser logging typo

---

CHANGELOG.md
src/multi_vector_simulator/C0_data_processing.py
src/multi_vector_simulator/E0_evaluation.py
src/multi_vector_simulator/E1_process_results.py
tests/test_E0_evaluation.py
tests/test_E1_process_results.py

- Circular imports are ok for windows but not for python

Fix circular imports

---

.github/workflows/main.yml
CHANGELOG.md
tests/test_D2_model_constraints.py
tests/test_E0_evaluation.py

Fix github action timeout
- Skip benchmark KPI test as it was seen to be consuming the whole test time leading to timeout(All tests beside KPI take 33s to run online versus 7.5s on my laptop)
- Reduce to one day the tests where simulation results are not important (for E and D test modules setup)
Maybe the computational power allocated to github action is too limited to run simulations, the solution would then be to keep the running simulation tests local

Fix GitHub actions

---

CHANGELOG.md
docs/MVS_Outputs.rst
src/multi_vector_simulator/E3_indicator_calculation.py

Fix #Issue
- Fix formula of degree of NZE in RTD
correct formula: `degree_of_nze = 1 + (total_feedin - total_grid_consumption) / total_demand`

Fix formula of degree of NZE in RTD

---

CHANGELOG.md
src/multi_vector_simulator/D0_modelling_and_optimization.py
src/multi_vector_simulator/utils/constants.py
src/multi_vector_simulator/utils/constants_json_strings.py
tests/test_C0_data_processing.py
tests/test_D0_modelling_and_optimization.py

There are a couple of tests that terminate or fail on windows only. This PR should fix that behaviour.
- Fix tests failing on windows with `FileExistsError`
- Changed pytests for `D0` to let them pass on Windows
- Added constant variables: `MODELLING_TIME`, `LP_FILE`

Fix failing pytests (limited to Windows)

---

tests/inputs/csv_elements/constraints.csv
tests/inputs/csv_elements/energyProduction.csv
tests/inputs/csv_elements/energyProviders.csv
tests/inputs/mvs_config.json

These inputs can still be used to test the `minimal_renewable_share` and `minimal_degree_of_autonomy` constraint as well as `maximumCap` constraints. PV timeseries unchanged.

Change tests/inputs

---

CHANGELOG.md
requirements/default.txt

Fix #836, fix #760, fix #200
I tried python 3.8 and 3.9, I let install the latest panda version (v1.2.3, .. happen only once ^^) and all the tests ran smoothly
Except one in `TestACElectricityBus.test_benchmark_AB_grid_pv` where it is a type mismatch which leads the two timeseries to not equal (one is int64, whereas the other float64) --> easily fixable. I would therefore suggest we use the latest panda version again.
- Forbid pyomo v 5.7.3
- add plotly to the default to generate pngs

Sort out dependencies in requirements.txt

---

tests/test_benchmark_scenarios.py

Fix failing test with pandas 1.2.3
- Changed the type of a series from int to float for series comparison not to fail

Fix failing test with latest pandas version

---

CHANGELOG.md
docs/index.rst

Related to #849 
Escape svg images from badges in latex

Use the badges only for html production and not latex

---

CHANGELOG.md
README.rst
docs/conf.py
docs/index.rst
requirements/docs.txt

Fix #849 
- Add rsvgconverter in sphinx extenstions to convert badges to pdf
- Cut better chapters for the docs

Fix ReadTheDocs build

---

.github/workflows/main.yml
CHANGELOG.md
requirements/test.txt

Fix #669 
- Add coveralls call to workflow

Setup coveralls on github actions

---

CHANGELOG.md
docs/index.rst

- Fix latex build due to svg badges by explicitely not including badges in pdf version of RTD

Use the badges only for the online RTD not the pdf version

---

.github/workflows/main.yml
CHANGELOG.md

It should prevent to have to wait for the test on the .py and coverage to pass if we change only the documentation .rst files
Leading to less waiting time and avoid using githubaction servers for nothing
- Your_changes

Prevent github action workflow for changes on docs

---

CHANGELOG.md
src/multi_vector_simulator/F0_output.py
tests/_constants.py
tests/benchmark_test_inputs/objective_value_exception_equal_annuity_total/csv_elements/constraints.csv
tests/benchmark_test_inputs/objective_value_exception_equal_annuity_total/csv_elements/economic_data.csv
tests/benchmark_test_inputs/objective_value_exception_equal_annuity_total/csv_elements/energyBusses.csv
tests/benchmark_test_inputs/objective_value_exception_equal_annuity_total/csv_elements/energyConsumption.csv
tests/benchmark_test_inputs/objective_value_exception_equal_annuity_total/csv_elements/energyConversion.csv
tests/benchmark_test_inputs/objective_value_exception_equal_annuity_total/csv_elements/energyProduction.csv
tests/benchmark_test_inputs/objective_value_exception_equal_annuity_total/csv_elements/energyProviders.csv
tests/benchmark_test_inputs/objective_value_exception_equal_annuity_total/csv_elements/energyStorage.csv
tests/benchmark_test_inputs/objective_value_exception_equal_annuity_total/csv_elements/fixcost.csv
tests/benchmark_test_inputs/objective_value_exception_equal_annuity_total/csv_elements/project_data.csv
tests/benchmark_test_inputs/objective_value_exception_equal_annuity_total/csv_elements/simulation_settings.csv
tests/test_A1_csv_to_json.py
tests/test_C1_verification.py
tests/test_F0_output.py
tests/test_benchmark_KPI.py
tests/test_benchmark_constraints.py
tests/test_benchmark_feedin.py
tests/test_benchmark_scenarios.py
tests/test_benchmark_special_features.py
tests/test_benchmark_stratified_thermal_storage.py

Fix #900
- Add simulation inputs for `tests/inputs/objective_value_exception_equal_annuity_total`
- Add pytest for `F0.TestLogCreation.test_parse_simulation_log` and benchmark test of `OBJECTIVE_VALUE`
- Fix `F0.TestLogCreation.test_parse_simulation_log`
- Constants `BENCHMARK_TEST_INPUT_FOLDER` and `BENCHMARK_TEST_OUTPUT_FOLDER` in `tests/_constants.py` (#901)

Print objective value in simulation output

---

CHANGELOG.md
requirements/default.txt

Addresses temporarily #908 by treating symptoms but not the cause
- Set numpy version to lower or equal than 1.19.4

Freeze numpy version

---

CHANGELOG.md
src/multi_vector_simulator/F2_autoreport.py

Fix #933 
- Specify tab name of Dash report to `scenario_name` (`scenario_id`) instead of `Dash`

Set Dash report tab name as: `scenario_name` (`scenario_id`)

---

CHANGELOG.md
src/multi_vector_simulator/E3_indicator_calculation.py
src/multi_vector_simulator/version.py
tests/test_E3_indicator_calculation.py

Fix #931 
- Add pytests to check if multiple energy providers with one energy carrier are evaluated correctly
- Fix `E3.add_total_consumption_from_provider_electricity_equivalent` and  `E3.add_total_feedin_electricity_equivalent`
- Update version number to `1.0.2dev` so that it is possible to clearly identify the simulations run before and after this fix (in the autoreport)

Bugfix: Multiple energy providers with one energy carrier not evaluated correctly

---

CHANGELOG.md
src/multi_vector_simulator/D0_modelling_and_optimization.py
src/multi_vector_simulator/F1_plotting.py
src/multi_vector_simulator/F2_autoreport.py
src/multi_vector_simulator/utils/constants.py

- When the user ask for images to be produced (`-pdf` or `-png` options) a sankey diagram is added to the report and to the `dict_values` under `[PATH_TO_PLOTS][PLOT_SANKEY]`
- `plot_sankey_diagramm` function in `D0_modelling_and_optimization.py` to add the dict of the sankey diagram
- `ready_sankey_diagram` in `F2_autoreport.py` to add sankey diagram to output and report
#930 should be merged first and this be rebased onto then

Add sankey diagram to output and report

---

src/multi_vector_simulator/utils/data_parser.py

- Let the optimized_add_cap be passed to epa results
- Get rid of the input_timeseries in the parameters returned to epa

Return the optimized add capacity of storage assets to the epa

---

CHANGELOG.md
src/multi_vector_simulator/utils/constants.py
src/multi_vector_simulator/utils/data_parser.py

Fix [161](https://github.com/open-plan-tool/gui/issues/161)
- The constraints are not all set to default values if only one constraint is missing, only the missing constraint is set to default value
- The default values for the constraints are now located in `src/constants.py` under the variable `DEFAULT_CONSTRAINT_VALUES`

Do not replace all constraints by default values automatically if one constraint only is missing

---

docs/conf.py
src/multi_vector_simulator/C0_data_processing.py
src/multi_vector_simulator/C1_verification.py
src/multi_vector_simulator/E3_indicator_calculation.py
src/multi_vector_simulator/utils/constants.py
src/multi_vector_simulator/utils/constants_json_strings.py
src/multi_vector_simulator/utils/helpers.py
tests/test_C0_data_processing.py
tests/test_C1_verification.py
tests/test_benchmark_feedin.py
tests/test_benchmark_scenarios.py

Prior to merge this PR #939  should be merged
Fix #941 
- Add functions to format name of automatically created assets in DSO setting for feedin cap and peak demand pricing
- Enable feedin cap by adding a transformer and an extra bus between existing bus and DSO feedin
- Add a special character to name of busses created automatically

Allow feedin capping for DSO

---

CHANGELOG.md
tests/test_C2_economic_functions.py

- The test `test_c2_economic_functions.py::test_get_replacement_costs_one_reinvestment_age_asset_equal_asset_lifetime` was added to account for a field usecase and a solution was provided

Fix a bug in replacement cost calculation reinvest in project last year

---

.readthedocs.yml

Our previous settings are deprecated since September 25th 2023 https://blog.readthedocs.com/migrate-configuration-v2/
Fix readthedocs build

Add mandatory build-os parameter to RTD config
