F0_output.py
F1_plotting.py

- creates capacity and annuity bar charts

Branch Marc new plots

---

code_folder/A_initialization.py
code_folder/B0_data_input_excel.py
code_folder/C0_data_processing.py
code_folder/E0_evaluation.py
mvs_eland_tool.py
tests/tests.py

* Package structure
* kwargs 'test' for default values in initialization

Update to enable test with pytest

---

code_folder/F0_output.py
code_folder/F1_plotting.py

Capacities and annuity costs plots have been updated

Plotting update: capacities and costs

---

.gitignore
CHANGELOG.md
CONTRIBUTING.md
README.md
docs/Developing.rst
docs/Installation.rst
docs/Makefile
docs/Overview.rst
docs/conf.py
docs/index.rst
docs/make.bat
docs/tables/table_tests.csv
mvs_eland_tool.py
requirements.txt
tests/test_requirements.txt
tests/tests.py

- Adapt requirements.txt to fit end user & developers users
- Add all files necessary for readthedocs
- Test content for readthedocs
- Update Changelog

Feature: Create readthedocs

---

docs/readthedocs.yml

Adding yml file to start documentation

Feature martha create readthedocs

---

CHANGELOG.md
docs/Installation.rst
docs/Overview.rst
docs/conf.py
requirements.txt

Towards solving #39 
- use autodoc to display functions and modules automatically

Implement readthedocs

---

CHANGELOG.md
README.md

The badges will be visible in the readme of the repository

Add badges to readme

---

CHANGELOG.md
README.md
setup.py

This will be useful to package the code on pypi :)

Add setup file

---

code_folder/A1_csv_to_json.py
inputs/elements/csv/fixcost.csv
inputs/elements/csv/project.csv
inputs/elements/working_example2.json
mvs_eland_tool.py

Updated:
* Removing project from input csv's
* Extend list of maximum_files
* Change of list of required_files
* Added test for maximum_files/parameter_list
* Added conversion of values when storing to json (parse strings as str/boolean/None/int/float)

Update csv to json: Input files and data tpye

---

code_folder/C0_data_processing.py
code_folder/D1_model_components.py

- Getting values and timeseries from lists (in case of multiple input or output busses)
- Transformers definition functions: functions for defining transformer of multiple or single busses are unified
Also, capex_var is no longer considered a potential timeseries.

Feature multiple busses review 2

---

.travis.yml
CHANGELOG.md
src/A0_initialization.py
tests/constants.py
tests/test_inputs.py
tests/test_simulation.py

The functions checking the input from the user are tested here

Add new tests for initializing

---

CHANGELOG.md
README.md

Link build badge to this repo

---

CHANGELOG.md
mvs_eland_tool/mvs_eland_tool.py
src/A0_initialization.py
src/A1_csv_to_json.py
src/C1_verification.py
tests/inputs/csv/simulation_settings.csv
tests/test_input_conversion.py
tests/test_inputs.py

Optimize workflow for input files/folder

---

docs/MVS_parameters.rst

Edited the docs file containing MVS parameters and their definitions.

Updated MVS_paramters.rst

---

src/constants.py

Addresses part of #137 by creating a module for constants in src

Create module to centralize global constants

---

docs/Installation.rst

I have added information on how to install MVS and some basic description, which I copied from README.md
Can you guys please add the instructions on how to execute the tool (with custom inputs )? This section can be found at the end of the docs/Installation.rst file.

Addingdocs

---

inputs/mvs_config.json

Fix json file

---

src/A0_initialization.py

Correcting typos

---

src/E1_process_results.py

Fixes if statements in E1 that were never True due to typo.

Fix searching for dict key "input_bus_name"

---

src/E1_process_results.py

Bug fix input_name instead of output_name

---

.github/issue_template.md
CHANGELOG.md

Fix #212 
- Add issue template to github

Add an issue template to github

---

src/D1_model_components.py

Change check_optimize_cap description

---

CHANGELOG.md
inputs/mvs_config.json

Fix #Issue
- Update json file. No peak demand pricing.
- :x: Use in-line comments to explain your code
- :x:  Write docstrings to your code
- :x:  For new functionalities: Explain in readthedocs
- :x:  Write test(s) for your new patch of code

Update mvs_config.json and set no peak demand pricing as default

---

docs/Code.rst

Fix None
- Change Code.rst to display new code tree
:x: Write docstrings to your code
:x:  Write test(s) for your new patch of code
:x: Update the CHANGELOG.md
:x: Apply black (`black . --exclude docs/`)

Update code tree in Code.rst

---

CHANGELOG.md
src/A0_initialization.py

Fix #227
- Change error message of FileNotFound Errors
:x: Write docstrings to your code
:x: Write test(s) for your new patch of code

Adapting FileNotFound Errors

---

CHANGELOG.md
src/B0_data_input_json.py
tests/constants.py
tests/test_B0_data_input_json.py

Integrating tests for B0

---

CHANGELOG.md
inputs/csv_elements/simulation_settings.csv
inputs/mvs_config.json
src/A1_csv_to_json.py
src/D0_modelling_and_optimization.py
src/F1_plotting.py

- Save network graph as png to output folder.
This is more convenient for me. However, if you prefer the plot to show up we could change it to:
- If plot_nx_graph is True: show plot, else don't
- always save the plot
- :x: Use in-line comments to explain your code
- :x:  Write docstrings to your code
- :x:  For new functionalities: Explain in readthedocs
- :x:  Write test(s) for your new patch of code

Save network graph as png to output folder

---

.github/pull_request_template.md
CHANGELOG.md
CONTRIBUTING.md
mvs_eland_tool/mvs_eland_tool.py
src/constants.py
tests/constants.py
tests/test_benchmark.py

Fix #159
- Fix the benchmark testing

Add a test of src/inputs files

---

CHANGELOG.md
tests/test_benchmark.py

Fix #260
- Overwrite local results when running through brenchmark tests

Fix issue 260 - local benchmark tests

---

CHANGELOG.md
README.md

Address part of #55
- Change URL of coveralls banner

Update coverall badge

---

CHANGELOG.md
src/F1_plotting.py

Fix #267, fix #285 
- add an if statements if there is no costs to plot. In this case a debug message is created

add if statement for plotting pie chart

---

CHANGELOG.md
src/B0_data_input_json.py
src/F0_output.py
tests/test_F0_output.py

Fix #280 
- Convert the dataframes to json format

Convert results lists in json_with_results to json format

---

.travis.yml
CHANGELOG.md

Related to #55 
- Make sure coverall badge is updated

Fix automatic update of test coverage badge

---

src/B0_data_input_json.py

Fix #318 
- Only update the dict if the field does not exist, otherwise it will always set the default value for this field.

Avoid replacing existing values by default dict

---

src/F2_autoreport.py
src/assets/styles.css

- Move the CSS styling code from f2_autoreport.py to the styles.css file within the assets folder. 
This enables the reuse of the style code snippets in different elements sharing the same styling features.

Move the CSS styling code to a style sheet and fix the create_app function

---

CHANGELOG.md
inputs/csv_elements/energyConsumption.csv
inputs/mvs_config.json
src/B0_data_input_json.py
src/F0_output.py
src/constants.py
tests/constants.py
tests/inputs/csv_elements/energyConsumption.csv
tests/inputs/mvs_config.json
tests/inputs_F1_plot_nx_false/csv_elements/energyConsumption.csv
tests/inputs_F1_plot_nx_true/csv_elements/energyConsumption.csv
tests/test_F0_output.py
tests/test_data/plot_data_for_F1.csv

Fix #311, fix #316 
- Create and manage the special types for json serialization and reverse conversion. 

Fix load_json

---

src/F2_autoreport.py

Fix #319
- Remove the old methods of creating pandas dataframes from xlsx output files
- Replace them with code creating dataframes from the json results files
:x: Write test(s) for your new patch of code

change inputs from xlsx to jsons in F2_autoreport.py

---

mvs_eland_tool/local_deploy.py
mvs_eland_tool/server_deploy.py
src/A0_initialization.py
src/A1_csv_to_json.py
src/B0_data_input_json.py
src/C0_data_processing.py
src/C1_verification.py
src/D0_modelling_and_optimization.py
src/D1_model_components.py
src/E0_evaluation.py
src/E1_process_results.py
src/E3_indicator_calculation.py
src/F0_output.py
src/F1_plotting.py
src/F2_autoreport.py
tests/test_A0_initialization.py
tests/test_A1_csv_to_json.py
tests/test_B0_data_input_json.py
tests/test_C0_data_processing.py
tests/test_C1_verification.py
tests/test_C2_economic_functions.py
tests/test_D0_modelling_and_optimization.py
tests/test_D1_model_components.py
tests/test_E0_evaluation.py
tests/test_E1_process_results.py
tests/test_E3_indicator_calculation.py
tests/test_F0_output.py
tests/test_F1_plotting.py
tests/test_benchmark.py
tests/test_benchmark_simple_scenarios.py

Addresses part of #336
- Using ctrl + alt + o on the filename in pycharm browser

Sort out imports and remove unused imports

---

tests/test_benchmark_simple_scenarios.py
tests/test_data/inputs_F1_plot_nx_false/csv_elements/energyProviders.csv
tests/test_data/inputs_F1_plot_nx_true/csv_elements/energyProviders.csv

Addresses part of #336 
- Fix failing test on master

Fix failing master tests

---

CHANGELOG.md
CONTRIBUTING.md

- Add a description of release protocol

Add release protocol

---

CHANGELOG.md
src/A1_csv_to_json.py
src/constants.py
tests/test_input_folder_parameters.py

- Change "new" for "extra"  to name the parameters which are not (yet) required parameters

Rename new parameter to extra parameter

---

CHANGELOG.md
docs/troubleshooting.rst

Fix #Issue
- Include pyppeteer for OS X

Update troubleshooting to include pyppeteer

---

CHANGELOG.md
docs/Installation.rst
docs/Overview.rst
docs/conf.py
docs/readthedocs_requirements.txt
docs/simulating_with_the_mvs.rst
docs/troubleshooting.rst
src/A0_initialization.py
src/A1_csv_to_json.py
src/C0_data_processing.py
src/C1_verification.py
src/E1_process_results.py
src/E3_indicator_calculation.py

Fix #425 
- Fix warnings from local build of the docs

Fix warnings in readthedocs local build

---

CHANGELOG.md
setup.py

Fix #430 
- Fetch the version number via other means than python

Fix pip install error

---

src/E2_economics.py
tests/test_E2_economics.py

Fix #Issue
- Fix LCOE keys to required dict keys

Fix dict keys in LCOE function

---

requirements.txt
setup.py
src/D0_modelling_and_optimization.py
src/E0_evaluation.py
src/E1_process_results.py

Improve towards #405 
Can be merged as soon as necessary. Please inform me in that case.

Update/to oemof 0.4.x - Continued work

---

CHANGELOG.md
docs/MVS_parameters.rst

Address #295 
- Add efficiency description to MVS_parameters

Battery efficiency description

---

CHANGELOG.md
src/E0_evaluation.py
tests/test_E0_evaluation.py
tests/test_F1_plotting.py

Fix #465
- Add if statement for key value None

Add None rounding in E0

---

CHANGELOG.md
src/E0_evaluation.py
src/F1_plotting.py
tests/test_B0_data_input_json.py
tests/test_E0_evaluation.py
tests/test_F1_plotting.py

Follow-up PR/fix after #468 
- No value attributed to key if not in asset_dict

Fix store result matrix

---

src/E0_evaluation.py
tests/test_E0_evaluation.py

Fix #465  
- Added that VALUE != None to be applied to round method

Fix E0.store_result_matrix() -> VALUE != None

---

src/F2_autoreport.py

HI @mahendrark! Please merge this PR if it makes sense to you.

Remove extensive pyppeteer console messages

---

CHANGELOG.md
src/E2_economics.py
src/F2_autoreport.py

Fix NaN issue

---

CHANGELOG.md
src/F2_autoreport.py

Fix #490 
Make the font styling uniform within the Plotly plots

Make the font styles uniform in the plots

---

CHANGELOG.md
src/C1_verification.py
tests/constants.py
tests/test_C1_verification.py

- Replaced strings in C1 that were not discovered in #497, sorry.
:x: Write docstrings to your code
:x: Write test(s) for your new patch of code
:x:  Update the CHANGELOG.md

String replacement from PR #497

---

src/C1_verification.py

@ursulaelmir  this fixes C1.check_feedin_tariff(). For me, the simulation runs through now.

Fix C1.check_feedin_tariff()

---

CHANGELOG.md
CONTRIBUTING.md

Update instruction for devs

---

CHANGELOG.md
docs/troubleshooting.rst

Fix #556 
- Add the instruction for troubleshooting on windows in the docs

Add graphviz troubleshoot for windows to docs

---

CHANGELOG.md
CONTRIBUTING.md

Follow up  #571 
- Update the release protocol in `CONTRIBUTING.md` file

Elaborate on the release procedure

---

CHANGELOG.md
src/multi_vector_simulator/E4_verification.py
tests/test_E4_verification.py

Fix #585 
- Add tests for `E4.detect_excessive_excess_generation_in_bus()`

Add tests for detect_excessive_excess_generation_in_bus

---

CHANGELOG.md
docs/MVS_Outputs.rst
docs/Model_Assumptions.rst

- Fix math equations in RTD
:x:  For new functionalities: Explain in readthedocs
:x:  Write test(s) for your new patch of code (pytests, assertion debug messages)
:x:  Apply black (`black . --exclude docs/`)

Fix math equations in readthedocs

---

CHANGELOG.md
CONTRIBUTING.md

Addresses #588 - however leave issue open as there was a question
- Add pypi release to release protocol and update/simplify protocol

Complete release protocol

---

CHANGELOG.md
docs/Model_Assumptions.rst
src/multi_vector_simulator/utils/constants.py

Add values of energy carrier weights 

---

CHANGELOG.md
docs/Model_Assumptions.rst

Fix #Issue
- Mistakenly deleted sentence
- Outdated source

Small fix for RTD - Energy carrier weighting

---

docs/Model_Equations.rst

Fix #Issue
- Alignment of equations
- Linebreaks
- Descriptive sentences for equations

Model equations - minor changes

---

CHANGELOG.md
docs/Model_Assumptions.rst

Fix #733
- Adapt section title of `Emissions` 
- Add references to table

Fix Model_Assumptions.rst

---

CONTRIBUTING.md

Address #694
- Exchange order of test.pypi.org and pypi checks

Update release protocol

---

CHANGELOG.md
requirements/default.txt

Fix #716
- fix requirement to xlrd==1.2.0 in default.txt
- [:x:] Use in-line comments to explain your code
- [:x:] Write docstrings to your code ([example docstring](https://multi-vector-simulator.readthedocs.io/en/latest/Developing.html#format-of-docstrings))
- [:x:] For new functionalities: Explain in readthedocs
- [:x:] Write test(s) for your new patch of code (pytests, assertion debug messages)

xlrd==1.2.0

---

CHANGELOG.md
src/multi_vector_simulator/D0_modelling_and_optimization.py
src/multi_vector_simulator/E0_evaluation.py
src/multi_vector_simulator/E1_process_results.py
src/multi_vector_simulator/E4_verification.py
src/multi_vector_simulator/utils/constants_json_strings.py
tests/test_E4_verification.py

Fix #294 
Fix #672 
- Code a function to check if there are any abnormal values in the SOC time-series
- If there are, then raise logging WARNINGS 
- Write tests for the above created function
- Fix a minor typo in an INFO logging message in D0

Function to check for abnormal SOC values

---

CHANGELOG.md
docs/MVS_parameters_list.csv

Fix #712 
- Add how to deactivate the RES constraint to the csv

Add HOW TO deactivate RES constraint to csv

---

CHANGELOG.md
docs/Model_Assumptions.rst

Fix #748 
- As the title says, add a small section containing brief descriptions of the tests carried out in E4 module of the source code.

Add a section in RTD describing the E4 verification tests

---

CHANGELOG.md
src/multi_vector_simulator/server.py
src/multi_vector_simulator/utils/analysis.py
tests/test_sensitivity.py

- Move sensitivity analysis to utils.analysis

Fix sensitivity analysis

---

CHANGELOG.md
docs/Model_Assumptions.rst
src/multi_vector_simulator/D0_modelling_and_optimization.py
src/multi_vector_simulator/utils/data_parser.py
tests/benchmark_test_inputs/epa_benchmark.json
tests/test_benchmark_scenarios.py

- Add test for json benchmark from EPA

Add a test for simulating the json from EPA

---

CHANGELOG.md
src/multi_vector_simulator/C0_data_processing.py
src/multi_vector_simulator/utils/__init__.py
src/multi_vector_simulator/utils/data_parser.py

Fix #rl-institut/mvs_eland_api/issues/10
Fix #rl-institut/mvs_eland_api/issues/11
- Fixes of the EPA-MVS parser, enabeling run-though of EPA-built scenarios
:x:  For new functionalities: Explain in readthedocs

Fix EPA-MVS-parser

---

CHANGELOG.md
docs/E-Land_Requirements.rst
docs/MVS_Outputs.rst
docs/Model_Assumptions.rst

Connected to #532 and #592
- Update `E-Land_Requirements.rst`
- Update `Model_Assumptions.rst` and `MVS_Outputs.rst`, mainly adding labels
:X: Use in-line comments to explain your code
:X: Write docstrings to your code ([example docstring](https://multi-vector-simulator.readthedocs.io/en/latest/Developing.html#format-of-docstrings))
:X:  For new functionalities: Explain in readthedocs
:X:  Write test(s) for your new patch of code (pytests, assertion debug messages)
:X:  Apply black (`black . --exclude docs/`)

Update the requirement statueses of the MVS

---

CHANGELOG.md
README.rst

Fix #Issue
- Add Zenodo badge
- Remove superfluous quotes of command lines instructions

Update README Zenodo's badge

---

CHANGELOG.md
src/multi_vector_simulator/D2_model_constraints.py
src/multi_vector_simulator/E0_evaluation.py

Fix #827 
- Loop over the user defined constraints to assign them instead of expecting all possible keys under `CONSTRAINTS` in `dict_values`

Fix missing constraints error

---

CHANGELOG.md
tests/test_D0_modelling_and_optimization.py

Fix pytest for Windows

---

CHANGELOG.md
README.rst
docs/index.rst

- Add badges for pypi, black linter and license 

Add more badges to the readme

---

CHANGELOG.md
README.rst
src/multi_vector_simulator/A0_initialization.py
src/multi_vector_simulator/cli.py
src/multi_vector_simulator/server.py

Update mvs welcome test and add --version option

---

CHANGELOG.md
docs/model/components.rst

Proofead model components RTD

---

CHANGELOG.md
docs/_static/table-style.css
docs/conf.py
docs/model/limitations.rst

Proofread limitations

---

CHANGELOG.md
docs/model/assumptions.rst
src/multi_vector_simulator/utils/constants.py

Fix #822 
- Correct the weighting factors

Correct weighting factors

---

CHANGELOG.md
src/multi_vector_simulator/server.py
src/multi_vector_simulator/utils/__init__.py
src/multi_vector_simulator/utils/data_parser.py

Debugging faulty input file from EPA to MVS

Faulty input file from EPA to MVS, terminating simulation

---

CHANGELOG.md
CONTRIBUTING.md
input_template/csv_elements/energyConversion.csv
input_template/csv_elements/energyProduction.csv
input_template/csv_elements/energyProviders.csv
input_template/csv_elements/storage_01.csv

Fix #494 
- Fix parameters in `input_template/csv_elements`: Missing parameters, generalize units
:x: Apply black (`black . --exclude docs/`)

Minor fixes: `input_template` and `CONTRIBUTING.md`

---

CHANGELOG.md
requirements/default.txt
requirements/report.txt

Fix requirements numpy

---

src/multi_vector_simulator/A1_csv_to_json.py

Minor fixes

---

README.rst

Addition of explanations for virtual environment usage for windows users to be able to use the full MVS tool capabilities
Fix #944

Update README file

---

requirements/default.txt

Fix #959
- Pin oemof version as the new release introduces breaking changes

Pin oemof version

---

docs/references/publications.rst

[x] Add reference for AHK Chile project
:x:  For new functionalities: Explain in readthedocs
:x:  Write test(s) for your new patch of code (pytests, assertion debug messages)
:x:  Apply black (`black . --exclude docs/`)

Add references
